# Generated by Django 5.0.3 on 2024-03-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainId', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('synop', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
