# Generated by Django 5.0.3 on 2024-03-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('trainsId', models.AutoField(primary_key=True, serialize=False)),
                ('origine', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('heure_de_depart', models.CharField(max_length=20)),
                ('heure_arrive', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Train',
        ),
    ]
